name: Trigger auto deployment for azure-containers-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/azure-containers-api-AutoDeployTrigger-e0d98274-3702-4de3-8e74-2e330a7e8a68.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURECONTAINERSAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: caadb98ba041acr.azurecr.io
          registryUsername: ${{ secrets.AZURECONTAINERSAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZURECONTAINERSAPI_REGISTRY_PASSWORD }}
          containerAppName: azure-containers-api
          resourceGroup: Azure_CR
          imageToBuild: caadb98ba041acr.azurecr.io/azure-containers-api:${{ github.sha }}
          
            

     

